# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'EndpointModelDeploymentArgsArgs',
    'EndpointModelDeploymentArgsArgsDict',
]

MYPY = False

if not MYPY:
    class EndpointModelDeploymentArgsArgsDict(TypedDict):
        endpoint_id: pulumi.Input[_builtins.str]
        """
        Vertex AI Endpoint ID
        """
        machine_type: NotRequired[pulumi.Input[_builtins.str]]
        """
        Machine type for deployment
        """
        max_replicas: NotRequired[pulumi.Input[_builtins.int]]
        """
        Maximum number of replicas
        """
        min_replicas: NotRequired[pulumi.Input[_builtins.int]]
        """
        Minimum number of replicas
        """
        traffic_percent: NotRequired[pulumi.Input[_builtins.int]]
        """
        Traffic percentage for this deployment
        """
elif False:
    EndpointModelDeploymentArgsArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class EndpointModelDeploymentArgsArgs:
    def __init__(__self__, *,
                 endpoint_id: pulumi.Input[_builtins.str],
                 machine_type: Optional[pulumi.Input[_builtins.str]] = None,
                 max_replicas: Optional[pulumi.Input[_builtins.int]] = None,
                 min_replicas: Optional[pulumi.Input[_builtins.int]] = None,
                 traffic_percent: Optional[pulumi.Input[_builtins.int]] = None):
        """
        :param pulumi.Input[_builtins.str] endpoint_id: Vertex AI Endpoint ID
        :param pulumi.Input[_builtins.str] machine_type: Machine type for deployment
        :param pulumi.Input[_builtins.int] max_replicas: Maximum number of replicas
        :param pulumi.Input[_builtins.int] min_replicas: Minimum number of replicas
        :param pulumi.Input[_builtins.int] traffic_percent: Traffic percentage for this deployment
        """
        pulumi.set(__self__, "endpoint_id", endpoint_id)
        if machine_type is None:
            machine_type = 'n1-standard-2'
        if machine_type is not None:
            pulumi.set(__self__, "machine_type", machine_type)
        if max_replicas is None:
            max_replicas = 3
        if max_replicas is not None:
            pulumi.set(__self__, "max_replicas", max_replicas)
        if min_replicas is None:
            min_replicas = 1
        if min_replicas is not None:
            pulumi.set(__self__, "min_replicas", min_replicas)
        if traffic_percent is None:
            traffic_percent = 100
        if traffic_percent is not None:
            pulumi.set(__self__, "traffic_percent", traffic_percent)

    @_builtins.property
    @pulumi.getter(name="endpointId")
    def endpoint_id(self) -> pulumi.Input[_builtins.str]:
        """
        Vertex AI Endpoint ID
        """
        return pulumi.get(self, "endpoint_id")

    @endpoint_id.setter
    def endpoint_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "endpoint_id", value)

    @_builtins.property
    @pulumi.getter(name="machineType")
    def machine_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Machine type for deployment
        """
        return pulumi.get(self, "machine_type")

    @machine_type.setter
    def machine_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "machine_type", value)

    @_builtins.property
    @pulumi.getter(name="maxReplicas")
    def max_replicas(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Maximum number of replicas
        """
        return pulumi.get(self, "max_replicas")

    @max_replicas.setter
    def max_replicas(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "max_replicas", value)

    @_builtins.property
    @pulumi.getter(name="minReplicas")
    def min_replicas(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Minimum number of replicas
        """
        return pulumi.get(self, "min_replicas")

    @min_replicas.setter
    def min_replicas(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "min_replicas", value)

    @_builtins.property
    @pulumi.getter(name="trafficPercent")
    def traffic_percent(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Traffic percentage for this deployment
        """
        return pulumi.get(self, "traffic_percent")

    @traffic_percent.setter
    def traffic_percent(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "traffic_percent", value)


