// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.davidmontoyago.gcpvertexmodeldeployment.resources.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class EndpointModelDeploymentArgsArgs extends com.pulumi.resources.ResourceArgs {

    public static final EndpointModelDeploymentArgsArgs Empty = new EndpointModelDeploymentArgsArgs();

    /**
     * Accelerator count for deployment
     * 
     */
    @Import(name="acceleratorCount")
    private @Nullable Output<Integer> acceleratorCount;

    /**
     * @return Accelerator count for deployment
     * 
     */
    public Optional<Output<Integer>> acceleratorCount() {
        return Optional.ofNullable(this.acceleratorCount);
    }

    /**
     * Accelerator type for endpoint deployment. Defaults to ACCELERATOR_TYPE_UNSPECIFIED. E.g.: NVIDIA_TESLA_P4, NVIDIA_TESLA_T4
     * 
     */
    @Import(name="acceleratorType")
    private @Nullable Output<String> acceleratorType;

    /**
     * @return Accelerator type for endpoint deployment. Defaults to ACCELERATOR_TYPE_UNSPECIFIED. E.g.: NVIDIA_TESLA_P4, NVIDIA_TESLA_T4
     * 
     */
    public Optional<Output<String>> acceleratorType() {
        return Optional.ofNullable(this.acceleratorType);
    }

    /**
     * Disable container logging
     * 
     */
    @Import(name="disableContainerLogging")
    private @Nullable Output<Boolean> disableContainerLogging;

    /**
     * @return Disable container logging
     * 
     */
    public Optional<Output<Boolean>> disableContainerLogging() {
        return Optional.ofNullable(this.disableContainerLogging);
    }

    /**
     * Enable access logging
     * 
     */
    @Import(name="enableAccessLogging")
    private @Nullable Output<Boolean> enableAccessLogging;

    /**
     * @return Enable access logging
     * 
     */
    public Optional<Output<Boolean>> enableAccessLogging() {
        return Optional.ofNullable(this.enableAccessLogging);
    }

    /**
     * Enable spot VMs
     * 
     */
    @Import(name="enableSpotVMs")
    private @Nullable Output<Boolean> enableSpotVMs;

    /**
     * @return Enable spot VMs
     * 
     */
    public Optional<Output<Boolean>> enableSpotVMs() {
        return Optional.ofNullable(this.enableSpotVMs);
    }

    /**
     * Vertex AI Endpoint ID
     * 
     */
    @Import(name="endpointId", required=true)
    private Output<String> endpointId;

    /**
     * @return Vertex AI Endpoint ID
     * 
     */
    public Output<String> endpointId() {
        return this.endpointId;
    }

    /**
     * Machine type for deployment
     * 
     */
    @Import(name="machineType")
    private @Nullable Output<String> machineType;

    /**
     * @return Machine type for deployment
     * 
     */
    public Optional<Output<String>> machineType() {
        return Optional.ofNullable(this.machineType);
    }

    /**
     * Maximum number of replicas
     * 
     */
    @Import(name="maxReplicas")
    private @Nullable Output<Integer> maxReplicas;

    /**
     * @return Maximum number of replicas
     * 
     */
    public Optional<Output<Integer>> maxReplicas() {
        return Optional.ofNullable(this.maxReplicas);
    }

    /**
     * Minimum number of replicas
     * 
     */
    @Import(name="minReplicas")
    private @Nullable Output<Integer> minReplicas;

    /**
     * @return Minimum number of replicas
     * 
     */
    public Optional<Output<Integer>> minReplicas() {
        return Optional.ofNullable(this.minReplicas);
    }

    /**
     * Traffic percentage for this deployment
     * 
     */
    @Import(name="trafficPercent")
    private @Nullable Output<Integer> trafficPercent;

    /**
     * @return Traffic percentage for this deployment
     * 
     */
    public Optional<Output<Integer>> trafficPercent() {
        return Optional.ofNullable(this.trafficPercent);
    }

    private EndpointModelDeploymentArgsArgs() {}

    private EndpointModelDeploymentArgsArgs(EndpointModelDeploymentArgsArgs $) {
        this.acceleratorCount = $.acceleratorCount;
        this.acceleratorType = $.acceleratorType;
        this.disableContainerLogging = $.disableContainerLogging;
        this.enableAccessLogging = $.enableAccessLogging;
        this.enableSpotVMs = $.enableSpotVMs;
        this.endpointId = $.endpointId;
        this.machineType = $.machineType;
        this.maxReplicas = $.maxReplicas;
        this.minReplicas = $.minReplicas;
        this.trafficPercent = $.trafficPercent;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(EndpointModelDeploymentArgsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private EndpointModelDeploymentArgsArgs $;

        public Builder() {
            $ = new EndpointModelDeploymentArgsArgs();
        }

        public Builder(EndpointModelDeploymentArgsArgs defaults) {
            $ = new EndpointModelDeploymentArgsArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param acceleratorCount Accelerator count for deployment
         * 
         * @return builder
         * 
         */
        public Builder acceleratorCount(@Nullable Output<Integer> acceleratorCount) {
            $.acceleratorCount = acceleratorCount;
            return this;
        }

        /**
         * @param acceleratorCount Accelerator count for deployment
         * 
         * @return builder
         * 
         */
        public Builder acceleratorCount(Integer acceleratorCount) {
            return acceleratorCount(Output.of(acceleratorCount));
        }

        /**
         * @param acceleratorType Accelerator type for endpoint deployment. Defaults to ACCELERATOR_TYPE_UNSPECIFIED. E.g.: NVIDIA_TESLA_P4, NVIDIA_TESLA_T4
         * 
         * @return builder
         * 
         */
        public Builder acceleratorType(@Nullable Output<String> acceleratorType) {
            $.acceleratorType = acceleratorType;
            return this;
        }

        /**
         * @param acceleratorType Accelerator type for endpoint deployment. Defaults to ACCELERATOR_TYPE_UNSPECIFIED. E.g.: NVIDIA_TESLA_P4, NVIDIA_TESLA_T4
         * 
         * @return builder
         * 
         */
        public Builder acceleratorType(String acceleratorType) {
            return acceleratorType(Output.of(acceleratorType));
        }

        /**
         * @param disableContainerLogging Disable container logging
         * 
         * @return builder
         * 
         */
        public Builder disableContainerLogging(@Nullable Output<Boolean> disableContainerLogging) {
            $.disableContainerLogging = disableContainerLogging;
            return this;
        }

        /**
         * @param disableContainerLogging Disable container logging
         * 
         * @return builder
         * 
         */
        public Builder disableContainerLogging(Boolean disableContainerLogging) {
            return disableContainerLogging(Output.of(disableContainerLogging));
        }

        /**
         * @param enableAccessLogging Enable access logging
         * 
         * @return builder
         * 
         */
        public Builder enableAccessLogging(@Nullable Output<Boolean> enableAccessLogging) {
            $.enableAccessLogging = enableAccessLogging;
            return this;
        }

        /**
         * @param enableAccessLogging Enable access logging
         * 
         * @return builder
         * 
         */
        public Builder enableAccessLogging(Boolean enableAccessLogging) {
            return enableAccessLogging(Output.of(enableAccessLogging));
        }

        /**
         * @param enableSpotVMs Enable spot VMs
         * 
         * @return builder
         * 
         */
        public Builder enableSpotVMs(@Nullable Output<Boolean> enableSpotVMs) {
            $.enableSpotVMs = enableSpotVMs;
            return this;
        }

        /**
         * @param enableSpotVMs Enable spot VMs
         * 
         * @return builder
         * 
         */
        public Builder enableSpotVMs(Boolean enableSpotVMs) {
            return enableSpotVMs(Output.of(enableSpotVMs));
        }

        /**
         * @param endpointId Vertex AI Endpoint ID
         * 
         * @return builder
         * 
         */
        public Builder endpointId(Output<String> endpointId) {
            $.endpointId = endpointId;
            return this;
        }

        /**
         * @param endpointId Vertex AI Endpoint ID
         * 
         * @return builder
         * 
         */
        public Builder endpointId(String endpointId) {
            return endpointId(Output.of(endpointId));
        }

        /**
         * @param machineType Machine type for deployment
         * 
         * @return builder
         * 
         */
        public Builder machineType(@Nullable Output<String> machineType) {
            $.machineType = machineType;
            return this;
        }

        /**
         * @param machineType Machine type for deployment
         * 
         * @return builder
         * 
         */
        public Builder machineType(String machineType) {
            return machineType(Output.of(machineType));
        }

        /**
         * @param maxReplicas Maximum number of replicas
         * 
         * @return builder
         * 
         */
        public Builder maxReplicas(@Nullable Output<Integer> maxReplicas) {
            $.maxReplicas = maxReplicas;
            return this;
        }

        /**
         * @param maxReplicas Maximum number of replicas
         * 
         * @return builder
         * 
         */
        public Builder maxReplicas(Integer maxReplicas) {
            return maxReplicas(Output.of(maxReplicas));
        }

        /**
         * @param minReplicas Minimum number of replicas
         * 
         * @return builder
         * 
         */
        public Builder minReplicas(@Nullable Output<Integer> minReplicas) {
            $.minReplicas = minReplicas;
            return this;
        }

        /**
         * @param minReplicas Minimum number of replicas
         * 
         * @return builder
         * 
         */
        public Builder minReplicas(Integer minReplicas) {
            return minReplicas(Output.of(minReplicas));
        }

        /**
         * @param trafficPercent Traffic percentage for this deployment
         * 
         * @return builder
         * 
         */
        public Builder trafficPercent(@Nullable Output<Integer> trafficPercent) {
            $.trafficPercent = trafficPercent;
            return this;
        }

        /**
         * @param trafficPercent Traffic percentage for this deployment
         * 
         * @return builder
         * 
         */
        public Builder trafficPercent(Integer trafficPercent) {
            return trafficPercent(Output.of(trafficPercent));
        }

        public EndpointModelDeploymentArgsArgs build() {
            if ($.endpointId == null) {
                throw new MissingRequiredPropertyException("EndpointModelDeploymentArgsArgs", "endpointId");
            }
            $.machineType = Codegen.stringProp("machineType").output().arg($.machineType).def("n1-standard-8").getNullable();
            $.maxReplicas = Codegen.integerProp("maxReplicas").output().arg($.maxReplicas).def(3).getNullable();
            $.minReplicas = Codegen.integerProp("minReplicas").output().arg($.minReplicas).def(1).getNullable();
            $.trafficPercent = Codegen.integerProp("trafficPercent").output().arg($.trafficPercent).def(100).getNullable();
            return $;
        }
    }

}
