# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import davidmontoyago_gcp_vertex_model_deployment.resources as __resources
    resources = __resources
else:
    resources = _utilities.lazy_import('davidmontoyago_gcp_vertex_model_deployment.resources')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "gcp-vertex-model-deployment",
  "mod": "resources",
  "fqn": "davidmontoyago_gcp_vertex_model_deployment.resources",
  "classes": {
   "gcp-vertex-model-deployment:resources:VertexModelDeployment": "VertexModelDeployment"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "gcp-vertex-model-deployment",
  "token": "pulumi:providers:gcp-vertex-model-deployment",
  "fqn": "davidmontoyago_gcp_vertex_model_deployment",
  "class": "Provider"
 }
]
"""
)
