// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { VertexModelDeploymentArgs } from "./vertexModelDeployment";
export type VertexModelDeployment = import("./vertexModelDeployment").VertexModelDeployment;
export const VertexModelDeployment: typeof import("./vertexModelDeployment").VertexModelDeployment = null as any;
utilities.lazyLoad(exports, ["VertexModelDeployment"], () => require("./vertexModelDeployment"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "gcp-vertex-model-deployment:resources:VertexModelDeployment":
                return new VertexModelDeployment(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("gcp-vertex-model-deployment", "resources", _module)
