// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Deploys a model to a Vertex AI endpoint
 */
export class VertexModelDeployment extends pulumi.CustomResource {
    /**
     * Get an existing VertexModelDeployment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): VertexModelDeployment {
        return new VertexModelDeployment(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'gcp-vertex-model-deployment:resources:VertexModelDeployment';

    /**
     * Returns true if the given object is an instance of VertexModelDeployment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is VertexModelDeployment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === VertexModelDeployment.__pulumiType;
    }

    /**
     * Creation timestamp
     */
    public /*out*/ readonly createTime!: pulumi.Output<string>;
    /**
     * ID of the deployed model
     */
    public /*out*/ readonly deployedModelId!: pulumi.Output<string>;
    /**
     * Configuration for deploying the model to a Vertex AI endpoint. Leave empty to upload model only for batched predictions.
     */
    public readonly endpointModelDeployment!: pulumi.Output<outputs.resources.EndpointModelDeploymentArgs | undefined>;
    /**
     * Full name of the endpoint
     */
    public /*out*/ readonly endpointName!: pulumi.Output<string>;
    public readonly healthRoute!: pulumi.Output<string | undefined>;
    /**
     * Labels for the deployment
     */
    public readonly labels!: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Bucket URI to the model artifacts. For instance, gs://my-bucket/my-model-artifacts/ - See: https://cloud.google.com/vertex-ai/docs/training/exporting-model-artifacts
     */
    public readonly modelArtifactsBucketUri!: pulumi.Output<string>;
    /**
     * Vertex AI Image URL of a custom or prebuilt container model server. See: https://cloud.google.com/vertex-ai/docs/predictions/pre-built-containers
     */
    public readonly modelImageUrl!: pulumi.Output<string>;
    public /*out*/ readonly modelName!: pulumi.Output<string>;
    /**
     * Bucket URI to the schema for the model inference behavior
     */
    public readonly modelPredictionBehaviorSchemaUri!: pulumi.Output<string | undefined>;
    /**
     * Bucket URI to the schema for the model input
     */
    public readonly modelPredictionInputSchemaUri!: pulumi.Output<string>;
    /**
     * Bucket URI to the schema for the model output
     */
    public readonly modelPredictionOutputSchemaUri!: pulumi.Output<string>;
    public readonly predictRoute!: pulumi.Output<string | undefined>;
    /**
     * Google Cloud Project ID
     */
    public readonly projectId!: pulumi.Output<string>;
    /**
     * Google Cloud region
     */
    public readonly region!: pulumi.Output<string>;
    /**
     * Service account for the model. If ModelImage is pointing to a private registry, this service account must have read access to the registry.
     */
    public readonly serviceAccount!: pulumi.Output<string>;

    /**
     * Create a VertexModelDeployment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: VertexModelDeploymentArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.modelArtifactsBucketUri === undefined) && !opts.urn) {
                throw new Error("Missing required property 'modelArtifactsBucketUri'");
            }
            if ((!args || args.modelImageUrl === undefined) && !opts.urn) {
                throw new Error("Missing required property 'modelImageUrl'");
            }
            if ((!args || args.modelPredictionInputSchemaUri === undefined) && !opts.urn) {
                throw new Error("Missing required property 'modelPredictionInputSchemaUri'");
            }
            if ((!args || args.modelPredictionOutputSchemaUri === undefined) && !opts.urn) {
                throw new Error("Missing required property 'modelPredictionOutputSchemaUri'");
            }
            if ((!args || args.projectId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'projectId'");
            }
            if ((!args || args.region === undefined) && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            if ((!args || args.serviceAccount === undefined) && !opts.urn) {
                throw new Error("Missing required property 'serviceAccount'");
            }
            resourceInputs["endpointModelDeployment"] = args ? (args.endpointModelDeployment ? pulumi.output(args.endpointModelDeployment).apply(inputs.resources.endpointModelDeploymentArgsArgsProvideDefaults) : undefined) : undefined;
            resourceInputs["healthRoute"] = args ? args.healthRoute : undefined;
            resourceInputs["labels"] = args ? args.labels : undefined;
            resourceInputs["modelArtifactsBucketUri"] = args ? args.modelArtifactsBucketUri : undefined;
            resourceInputs["modelImageUrl"] = args ? args.modelImageUrl : undefined;
            resourceInputs["modelPredictionBehaviorSchemaUri"] = args ? args.modelPredictionBehaviorSchemaUri : undefined;
            resourceInputs["modelPredictionInputSchemaUri"] = args ? args.modelPredictionInputSchemaUri : undefined;
            resourceInputs["modelPredictionOutputSchemaUri"] = args ? args.modelPredictionOutputSchemaUri : undefined;
            resourceInputs["predictRoute"] = args ? args.predictRoute : undefined;
            resourceInputs["projectId"] = args ? args.projectId : undefined;
            resourceInputs["region"] = args ? args.region : undefined;
            resourceInputs["serviceAccount"] = args ? args.serviceAccount : undefined;
            resourceInputs["createTime"] = undefined /*out*/;
            resourceInputs["deployedModelId"] = undefined /*out*/;
            resourceInputs["endpointName"] = undefined /*out*/;
            resourceInputs["modelName"] = undefined /*out*/;
        } else {
            resourceInputs["createTime"] = undefined /*out*/;
            resourceInputs["deployedModelId"] = undefined /*out*/;
            resourceInputs["endpointModelDeployment"] = undefined /*out*/;
            resourceInputs["endpointName"] = undefined /*out*/;
            resourceInputs["healthRoute"] = undefined /*out*/;
            resourceInputs["labels"] = undefined /*out*/;
            resourceInputs["modelArtifactsBucketUri"] = undefined /*out*/;
            resourceInputs["modelImageUrl"] = undefined /*out*/;
            resourceInputs["modelName"] = undefined /*out*/;
            resourceInputs["modelPredictionBehaviorSchemaUri"] = undefined /*out*/;
            resourceInputs["modelPredictionInputSchemaUri"] = undefined /*out*/;
            resourceInputs["modelPredictionOutputSchemaUri"] = undefined /*out*/;
            resourceInputs["predictRoute"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["region"] = undefined /*out*/;
            resourceInputs["serviceAccount"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(VertexModelDeployment.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a VertexModelDeployment resource.
 */
export interface VertexModelDeploymentArgs {
    /**
     * Configuration for deploying the model to a Vertex AI endpoint. Leave empty to upload model only for batched predictions.
     */
    endpointModelDeployment?: pulumi.Input<inputs.resources.EndpointModelDeploymentArgsArgs>;
    healthRoute?: pulumi.Input<string>;
    /**
     * Labels for the deployment
     */
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * Bucket URI to the model artifacts. For instance, gs://my-bucket/my-model-artifacts/ - See: https://cloud.google.com/vertex-ai/docs/training/exporting-model-artifacts
     */
    modelArtifactsBucketUri: pulumi.Input<string>;
    /**
     * Vertex AI Image URL of a custom or prebuilt container model server. See: https://cloud.google.com/vertex-ai/docs/predictions/pre-built-containers
     */
    modelImageUrl: pulumi.Input<string>;
    /**
     * Bucket URI to the schema for the model inference behavior
     */
    modelPredictionBehaviorSchemaUri?: pulumi.Input<string>;
    /**
     * Bucket URI to the schema for the model input
     */
    modelPredictionInputSchemaUri: pulumi.Input<string>;
    /**
     * Bucket URI to the schema for the model output
     */
    modelPredictionOutputSchemaUri: pulumi.Input<string>;
    predictRoute?: pulumi.Input<string>;
    /**
     * Google Cloud Project ID
     */
    projectId: pulumi.Input<string>;
    /**
     * Google Cloud region
     */
    region: pulumi.Input<string>;
    /**
     * Service account for the model. If ModelImage is pointing to a private registry, this service account must have read access to the registry.
     */
    serviceAccount: pulumi.Input<string>;
}
