// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Davidmontoyago.GcpVertexModelDeployment.Resources.Outputs
{

    [OutputType]
    public sealed class EndpointModelDeploymentArgs
    {
        /// <summary>
        /// Vertex AI Endpoint ID
        /// </summary>
        public readonly string EndpointId;
        /// <summary>
        /// Machine type for deployment
        /// </summary>
        public readonly string? MachineType;
        /// <summary>
        /// Maximum number of replicas
        /// </summary>
        public readonly int? MaxReplicas;
        /// <summary>
        /// Minimum number of replicas
        /// </summary>
        public readonly int? MinReplicas;
        /// <summary>
        /// Traffic percentage for this deployment
        /// </summary>
        public readonly int? TrafficPercent;

        [OutputConstructor]
        private EndpointModelDeploymentArgs(
            string endpointId,

            string? machineType,

            int? maxReplicas,

            int? minReplicas,

            int? trafficPercent)
        {
            EndpointId = endpointId;
            MachineType = machineType;
            MaxReplicas = maxReplicas;
            MinReplicas = minReplicas;
            TrafficPercent = trafficPercent;
        }
    }
}
