// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"context"
	"reflect"

	"github.com/davidmontoyago/pulumi-gcp-vertex-model-deployment/sdk/go/pulumi-gcp-vertex-model-deployment/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type EndpointModelDeploymentArgs struct {
	// Vertex AI Endpoint ID
	EndpointId string `pulumi:"endpointId"`
	// Machine type for deployment
	MachineType *string `pulumi:"machineType"`
	// Maximum number of replicas
	MaxReplicas *int `pulumi:"maxReplicas"`
	// Minimum number of replicas
	MinReplicas *int `pulumi:"minReplicas"`
	// Traffic percentage for this deployment
	TrafficPercent *int `pulumi:"trafficPercent"`
}

// Defaults sets the appropriate defaults for EndpointModelDeploymentArgs
func (val *EndpointModelDeploymentArgs) Defaults() *EndpointModelDeploymentArgs {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.MachineType == nil {
		machineType_ := "n1-standard-2"
		tmp.MachineType = &machineType_
	}
	if tmp.MaxReplicas == nil {
		maxReplicas_ := 3
		tmp.MaxReplicas = &maxReplicas_
	}
	if tmp.MinReplicas == nil {
		minReplicas_ := 1
		tmp.MinReplicas = &minReplicas_
	}
	if tmp.TrafficPercent == nil {
		trafficPercent_ := 100
		tmp.TrafficPercent = &trafficPercent_
	}
	return &tmp
}

// EndpointModelDeploymentArgsInput is an input type that accepts EndpointModelDeploymentArgsArgs and EndpointModelDeploymentArgsOutput values.
// You can construct a concrete instance of `EndpointModelDeploymentArgsInput` via:
//
//	EndpointModelDeploymentArgsArgs{...}
type EndpointModelDeploymentArgsInput interface {
	pulumi.Input

	ToEndpointModelDeploymentArgsOutput() EndpointModelDeploymentArgsOutput
	ToEndpointModelDeploymentArgsOutputWithContext(context.Context) EndpointModelDeploymentArgsOutput
}

type EndpointModelDeploymentArgsArgs struct {
	// Vertex AI Endpoint ID
	EndpointId pulumi.StringInput `pulumi:"endpointId"`
	// Machine type for deployment
	MachineType pulumi.StringPtrInput `pulumi:"machineType"`
	// Maximum number of replicas
	MaxReplicas pulumi.IntPtrInput `pulumi:"maxReplicas"`
	// Minimum number of replicas
	MinReplicas pulumi.IntPtrInput `pulumi:"minReplicas"`
	// Traffic percentage for this deployment
	TrafficPercent pulumi.IntPtrInput `pulumi:"trafficPercent"`
}

// Defaults sets the appropriate defaults for EndpointModelDeploymentArgsArgs
func (val *EndpointModelDeploymentArgsArgs) Defaults() *EndpointModelDeploymentArgsArgs {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.MachineType == nil {
		tmp.MachineType = pulumi.StringPtr("n1-standard-2")
	}
	if tmp.MaxReplicas == nil {
		tmp.MaxReplicas = pulumi.IntPtr(3)
	}
	if tmp.MinReplicas == nil {
		tmp.MinReplicas = pulumi.IntPtr(1)
	}
	if tmp.TrafficPercent == nil {
		tmp.TrafficPercent = pulumi.IntPtr(100)
	}
	return &tmp
}
func (EndpointModelDeploymentArgsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*EndpointModelDeploymentArgs)(nil)).Elem()
}

func (i EndpointModelDeploymentArgsArgs) ToEndpointModelDeploymentArgsOutput() EndpointModelDeploymentArgsOutput {
	return i.ToEndpointModelDeploymentArgsOutputWithContext(context.Background())
}

func (i EndpointModelDeploymentArgsArgs) ToEndpointModelDeploymentArgsOutputWithContext(ctx context.Context) EndpointModelDeploymentArgsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EndpointModelDeploymentArgsOutput)
}

func (i EndpointModelDeploymentArgsArgs) ToEndpointModelDeploymentArgsPtrOutput() EndpointModelDeploymentArgsPtrOutput {
	return i.ToEndpointModelDeploymentArgsPtrOutputWithContext(context.Background())
}

func (i EndpointModelDeploymentArgsArgs) ToEndpointModelDeploymentArgsPtrOutputWithContext(ctx context.Context) EndpointModelDeploymentArgsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EndpointModelDeploymentArgsOutput).ToEndpointModelDeploymentArgsPtrOutputWithContext(ctx)
}

// EndpointModelDeploymentArgsPtrInput is an input type that accepts EndpointModelDeploymentArgsArgs, EndpointModelDeploymentArgsPtr and EndpointModelDeploymentArgsPtrOutput values.
// You can construct a concrete instance of `EndpointModelDeploymentArgsPtrInput` via:
//
//	        EndpointModelDeploymentArgsArgs{...}
//
//	or:
//
//	        nil
type EndpointModelDeploymentArgsPtrInput interface {
	pulumi.Input

	ToEndpointModelDeploymentArgsPtrOutput() EndpointModelDeploymentArgsPtrOutput
	ToEndpointModelDeploymentArgsPtrOutputWithContext(context.Context) EndpointModelDeploymentArgsPtrOutput
}

type endpointModelDeploymentArgsPtrType EndpointModelDeploymentArgsArgs

func EndpointModelDeploymentArgsPtr(v *EndpointModelDeploymentArgsArgs) EndpointModelDeploymentArgsPtrInput {
	return (*endpointModelDeploymentArgsPtrType)(v)
}

func (*endpointModelDeploymentArgsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**EndpointModelDeploymentArgs)(nil)).Elem()
}

func (i *endpointModelDeploymentArgsPtrType) ToEndpointModelDeploymentArgsPtrOutput() EndpointModelDeploymentArgsPtrOutput {
	return i.ToEndpointModelDeploymentArgsPtrOutputWithContext(context.Background())
}

func (i *endpointModelDeploymentArgsPtrType) ToEndpointModelDeploymentArgsPtrOutputWithContext(ctx context.Context) EndpointModelDeploymentArgsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EndpointModelDeploymentArgsPtrOutput)
}

type EndpointModelDeploymentArgsOutput struct{ *pulumi.OutputState }

func (EndpointModelDeploymentArgsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*EndpointModelDeploymentArgs)(nil)).Elem()
}

func (o EndpointModelDeploymentArgsOutput) ToEndpointModelDeploymentArgsOutput() EndpointModelDeploymentArgsOutput {
	return o
}

func (o EndpointModelDeploymentArgsOutput) ToEndpointModelDeploymentArgsOutputWithContext(ctx context.Context) EndpointModelDeploymentArgsOutput {
	return o
}

func (o EndpointModelDeploymentArgsOutput) ToEndpointModelDeploymentArgsPtrOutput() EndpointModelDeploymentArgsPtrOutput {
	return o.ToEndpointModelDeploymentArgsPtrOutputWithContext(context.Background())
}

func (o EndpointModelDeploymentArgsOutput) ToEndpointModelDeploymentArgsPtrOutputWithContext(ctx context.Context) EndpointModelDeploymentArgsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v EndpointModelDeploymentArgs) *EndpointModelDeploymentArgs {
		return &v
	}).(EndpointModelDeploymentArgsPtrOutput)
}

// Vertex AI Endpoint ID
func (o EndpointModelDeploymentArgsOutput) EndpointId() pulumi.StringOutput {
	return o.ApplyT(func(v EndpointModelDeploymentArgs) string { return v.EndpointId }).(pulumi.StringOutput)
}

// Machine type for deployment
func (o EndpointModelDeploymentArgsOutput) MachineType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v EndpointModelDeploymentArgs) *string { return v.MachineType }).(pulumi.StringPtrOutput)
}

// Maximum number of replicas
func (o EndpointModelDeploymentArgsOutput) MaxReplicas() pulumi.IntPtrOutput {
	return o.ApplyT(func(v EndpointModelDeploymentArgs) *int { return v.MaxReplicas }).(pulumi.IntPtrOutput)
}

// Minimum number of replicas
func (o EndpointModelDeploymentArgsOutput) MinReplicas() pulumi.IntPtrOutput {
	return o.ApplyT(func(v EndpointModelDeploymentArgs) *int { return v.MinReplicas }).(pulumi.IntPtrOutput)
}

// Traffic percentage for this deployment
func (o EndpointModelDeploymentArgsOutput) TrafficPercent() pulumi.IntPtrOutput {
	return o.ApplyT(func(v EndpointModelDeploymentArgs) *int { return v.TrafficPercent }).(pulumi.IntPtrOutput)
}

type EndpointModelDeploymentArgsPtrOutput struct{ *pulumi.OutputState }

func (EndpointModelDeploymentArgsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**EndpointModelDeploymentArgs)(nil)).Elem()
}

func (o EndpointModelDeploymentArgsPtrOutput) ToEndpointModelDeploymentArgsPtrOutput() EndpointModelDeploymentArgsPtrOutput {
	return o
}

func (o EndpointModelDeploymentArgsPtrOutput) ToEndpointModelDeploymentArgsPtrOutputWithContext(ctx context.Context) EndpointModelDeploymentArgsPtrOutput {
	return o
}

func (o EndpointModelDeploymentArgsPtrOutput) Elem() EndpointModelDeploymentArgsOutput {
	return o.ApplyT(func(v *EndpointModelDeploymentArgs) EndpointModelDeploymentArgs {
		if v != nil {
			return *v
		}
		var ret EndpointModelDeploymentArgs
		return ret
	}).(EndpointModelDeploymentArgsOutput)
}

// Vertex AI Endpoint ID
func (o EndpointModelDeploymentArgsPtrOutput) EndpointId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *EndpointModelDeploymentArgs) *string {
		if v == nil {
			return nil
		}
		return &v.EndpointId
	}).(pulumi.StringPtrOutput)
}

// Machine type for deployment
func (o EndpointModelDeploymentArgsPtrOutput) MachineType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *EndpointModelDeploymentArgs) *string {
		if v == nil {
			return nil
		}
		return v.MachineType
	}).(pulumi.StringPtrOutput)
}

// Maximum number of replicas
func (o EndpointModelDeploymentArgsPtrOutput) MaxReplicas() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *EndpointModelDeploymentArgs) *int {
		if v == nil {
			return nil
		}
		return v.MaxReplicas
	}).(pulumi.IntPtrOutput)
}

// Minimum number of replicas
func (o EndpointModelDeploymentArgsPtrOutput) MinReplicas() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *EndpointModelDeploymentArgs) *int {
		if v == nil {
			return nil
		}
		return v.MinReplicas
	}).(pulumi.IntPtrOutput)
}

// Traffic percentage for this deployment
func (o EndpointModelDeploymentArgsPtrOutput) TrafficPercent() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *EndpointModelDeploymentArgs) *int {
		if v == nil {
			return nil
		}
		return v.TrafficPercent
	}).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EndpointModelDeploymentArgsInput)(nil)).Elem(), EndpointModelDeploymentArgsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*EndpointModelDeploymentArgsPtrInput)(nil)).Elem(), EndpointModelDeploymentArgsArgs{})
	pulumi.RegisterOutputType(EndpointModelDeploymentArgsOutput{})
	pulumi.RegisterOutputType(EndpointModelDeploymentArgsPtrOutput{})
}
