// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import * as utilities from "../utilities";

export namespace resources {
    export interface EndpointModelDeploymentArgsArgs {
        /**
         * Vertex AI Endpoint ID
         */
        endpointId: pulumi.Input<string>;
        /**
         * Machine type for deployment
         */
        machineType?: pulumi.Input<string>;
        /**
         * Maximum number of replicas
         */
        maxReplicas?: pulumi.Input<number>;
        /**
         * Minimum number of replicas
         */
        minReplicas?: pulumi.Input<number>;
        /**
         * Traffic percentage for this deployment
         */
        trafficPercent?: pulumi.Input<number>;
    }
    /**
     * endpointModelDeploymentArgsArgsProvideDefaults sets the appropriate defaults for EndpointModelDeploymentArgsArgs
     */
    export function endpointModelDeploymentArgsArgsProvideDefaults(val: EndpointModelDeploymentArgsArgs): EndpointModelDeploymentArgsArgs {
        return {
            ...val,
            machineType: (val.machineType) ?? "n1-standard-2",
            maxReplicas: (val.maxReplicas) ?? 3,
            minReplicas: (val.minReplicas) ?? 1,
            trafficPercent: (val.trafficPercent) ?? 100,
        };
    }
}
