// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import * as utilities from "../utilities";

export namespace resources {
    export interface EndpointModelDeploymentArgs {
        /**
         * Accelerator count for deployment
         */
        acceleratorCount?: number;
        /**
         * Accelerator type for endpoint deployment. Defaults to ACCELERATOR_TYPE_UNSPECIFIED. E.g.: NVIDIA_TESLA_P4, NVIDIA_TESLA_T4
         */
        acceleratorType?: string;
        /**
         * Vertex AI Endpoint ID
         */
        endpointId: string;
        /**
         * Machine type for deployment
         */
        machineType?: string;
        /**
         * Maximum number of replicas
         */
        maxReplicas?: number;
        /**
         * Minimum number of replicas
         */
        minReplicas?: number;
        /**
         * Traffic percentage for this deployment
         */
        trafficPercent?: number;
    }
    /**
     * endpointModelDeploymentArgsProvideDefaults sets the appropriate defaults for EndpointModelDeploymentArgs
     */
    export function endpointModelDeploymentArgsProvideDefaults(val: EndpointModelDeploymentArgs): EndpointModelDeploymentArgs {
        return {
            ...val,
            machineType: (val.machineType) ?? "n1-standard-8",
            maxReplicas: (val.maxReplicas) ?? 3,
            minReplicas: (val.minReplicas) ?? 1,
            trafficPercent: (val.trafficPercent) ?? 100,
        };
    }

}
