// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.davidmontoyago.gcpvertexmodeldeployment.resources.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class EndpointModelDeploymentArgs {
    /**
     * @return Vertex AI Endpoint ID
     * 
     */
    private String endpointId;
    /**
     * @return Machine type for deployment
     * 
     */
    private @Nullable String machineType;
    /**
     * @return Maximum number of replicas
     * 
     */
    private @Nullable Integer maxReplicas;
    /**
     * @return Minimum number of replicas
     * 
     */
    private @Nullable Integer minReplicas;
    /**
     * @return Traffic percentage for this deployment
     * 
     */
    private @Nullable Integer trafficPercent;

    private EndpointModelDeploymentArgs() {}
    /**
     * @return Vertex AI Endpoint ID
     * 
     */
    public String endpointId() {
        return this.endpointId;
    }
    /**
     * @return Machine type for deployment
     * 
     */
    public Optional<String> machineType() {
        return Optional.ofNullable(this.machineType);
    }
    /**
     * @return Maximum number of replicas
     * 
     */
    public Optional<Integer> maxReplicas() {
        return Optional.ofNullable(this.maxReplicas);
    }
    /**
     * @return Minimum number of replicas
     * 
     */
    public Optional<Integer> minReplicas() {
        return Optional.ofNullable(this.minReplicas);
    }
    /**
     * @return Traffic percentage for this deployment
     * 
     */
    public Optional<Integer> trafficPercent() {
        return Optional.ofNullable(this.trafficPercent);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(EndpointModelDeploymentArgs defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String endpointId;
        private @Nullable String machineType;
        private @Nullable Integer maxReplicas;
        private @Nullable Integer minReplicas;
        private @Nullable Integer trafficPercent;
        public Builder() {}
        public Builder(EndpointModelDeploymentArgs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.endpointId = defaults.endpointId;
    	      this.machineType = defaults.machineType;
    	      this.maxReplicas = defaults.maxReplicas;
    	      this.minReplicas = defaults.minReplicas;
    	      this.trafficPercent = defaults.trafficPercent;
        }

        @CustomType.Setter
        public Builder endpointId(String endpointId) {
            if (endpointId == null) {
              throw new MissingRequiredPropertyException("EndpointModelDeploymentArgs", "endpointId");
            }
            this.endpointId = endpointId;
            return this;
        }
        @CustomType.Setter
        public Builder machineType(@Nullable String machineType) {

            this.machineType = machineType;
            return this;
        }
        @CustomType.Setter
        public Builder maxReplicas(@Nullable Integer maxReplicas) {

            this.maxReplicas = maxReplicas;
            return this;
        }
        @CustomType.Setter
        public Builder minReplicas(@Nullable Integer minReplicas) {

            this.minReplicas = minReplicas;
            return this;
        }
        @CustomType.Setter
        public Builder trafficPercent(@Nullable Integer trafficPercent) {

            this.trafficPercent = trafficPercent;
            return this;
        }
        public EndpointModelDeploymentArgs build() {
            final var _resultValue = new EndpointModelDeploymentArgs();
            _resultValue.endpointId = endpointId;
            _resultValue.machineType = machineType;
            _resultValue.maxReplicas = maxReplicas;
            _resultValue.minReplicas = minReplicas;
            _resultValue.trafficPercent = trafficPercent;
            return _resultValue;
        }
    }
}
